// popup.js - 處理 popup 界面的邏輯

class PopupController {
  constructor() {
    this.enableBtn = document.getElementById('enablePersistentMode');
    this.disableBtn = document.getElementById('disablePersistentMode');
    this.actionStatus = document.getElementById('actionStatus');
    this.historyList = document.getElementById('historyList');
    
    this.isPersistentMode = false;
    this.init();
  }

  async init() {
    this.enableBtn.addEventListener('click', () => this.enablePersistentMode());
    this.disableBtn.addEventListener('click', () => this.disablePersistentMode());

    document.getElementById('exportJSON')?.addEventListener('click', () => this.exportHistory('json'));
    document.getElementById('exportCSV')?.addEventListener('click', () => this.exportHistory('csv'));
    document.getElementById('exportPOM')?.addEventListener('click', () => this.exportHistory('pom'));
    document.getElementById('clearHistory')?.addEventListener('click', () => this.clearHistory());

    await this.checkPersistentModeStatus();
    await this.loadHistory();
  }

  async checkPersistentModeStatus() {
    try {
      const result = await chrome.storage.sync.get(['persistentModeEnabled']);
      this.isPersistentMode = result.persistentModeEnabled || false;
      this.updateUI();
    } catch (error) {
      console.error('檢查持續模式狀態失敗:', error);
    }
  }

  async loadHistory() {
    try {
      const response = await chrome.runtime.sendMessage({ action: 'getHistory' });
      const history = response?.history || [];
      if (!this.historyList) return;
      if (history.length === 0) {
        this.historyList.innerHTML = '<div class="history-empty">尚無歷史紀錄</div>';
        return;
      }
      this.historyList.innerHTML = history.slice(0, 10).map(e => {
        const time = new Date(e.id).toLocaleString('zh-TW', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
        const host = e.url ? (() => { try { return new URL(e.url).hostname } catch (_) { return e.url } })() : '?';
        const pw = e.locators?.playwright?.value || e.locators?.css?.value || '';
        const preview = pw ? pw.substring(0, 50) + (pw.length > 50 ? '…' : '') : '';
        return `<div class="history-entry">
          <div class="history-meta"><span class="history-tag">&lt;${e.tagName || '?'}&gt;</span><span class="history-host">${host}</span><span class="history-time">${time}</span></div>
          ${preview ? `<div class="history-preview">${preview}</div>` : ''}
        </div>`;
      }).join('');
    } catch (error) {
      console.error('載入歷史失敗:', error);
    }
  }

  async exportHistory(format) {
    try {
      const response = await chrome.runtime.sendMessage({ action: 'getHistory' });
      const history = response?.history || [];
      if (history.length === 0) {
        alert('尚無歷史紀錄可匯出');
        return;
      }

      let content, filename, mimeType;

      if (format === 'json') {
        content = JSON.stringify(history.map(e => ({
          id: e.id,
          timestamp: new Date(e.id).toISOString(),
          url: e.url || '',
          tagName: e.tagName || '',
          locators: e.locators || {}
        })), null, 2);
        filename = 'locators.json';
        mimeType = 'application/json';

      } else if (format === 'csv') {
        const rows = ['timestamp,url,tag,type,locator'];
        history.forEach(e => {
          const ts = new Date(e.id).toISOString();
          const url = this._csvEscape(e.url || '');
          const tag = this._csvEscape(e.tagName || '');
          if (e.locators) {
            Object.entries(e.locators).forEach(([type, data]) => {
              rows.push(`${ts},${url},${tag},${type},${this._csvEscape(data?.value || '')}`);
            });
          }
        });
        content = rows.join('\n');
        filename = 'locators.csv';
        mimeType = 'text/csv';

      } else if (format === 'pom') {
        const lines = [
          '// Generated by Element Locator Generator',
          `// Exported at ${new Date().toISOString()}`,
          '',
          'class PageObjects {'
        ];
        history.forEach((e, i) => {
          const name = (e.tagName || 'element').toLowerCase().replace(/[^a-z0-9]/g, '') + i;
          const primary = e.locators?.playwright?.value || e.locators?.css?.value || '';
          lines.push(`  /** ${e.url || ''} — <${e.tagName || '?'}> */`);
          if (primary) lines.push(`  get ${name}() { return page.locator(${JSON.stringify(primary)}) }`);
        });
        lines.push('}', '', 'module.exports = { PageObjects }');
        content = lines.join('\n');
        filename = 'page-objects.js';
        mimeType = 'text/javascript';
      }

      // 觸發下載（需在新分頁開啟，因為 popup 視窗受限）
      const dataUrl = 'data:' + mimeType + ';charset=utf-8,' + encodeURIComponent(content);
      await chrome.downloads.download({ url: dataUrl, filename });
    } catch (error) {
      console.error('匯出失敗:', error);
      alert('匯出失敗：' + error.message);
    }
  }

  async clearHistory() {
    if (!confirm('確定要清除所有歷史紀錄？')) return;
    try {
      await chrome.runtime.sendMessage({ action: 'clearHistory' });
      await this.loadHistory();
    } catch (error) {
      console.error('清除歷史失敗:', error);
    }
  }

  _csvEscape(val) {
    const str = String(val);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return '"' + str.replace(/"/g, '""') + '"';
    }
    return str;
  }

  async enablePersistentMode() {
    try {
      await chrome.storage.sync.set({ persistentModeEnabled: true });
      const response = await chrome.runtime.sendMessage({ action: 'enablePersistentMode' });
      if (response && response.success) {
        this.isPersistentMode = true;
        this.updateUI();
        this.showActionStatus('持續模式已啟動', 'success');
        setTimeout(() => window.close(), 2000);
      } else {
        this.showActionStatus('啟動失敗', 'error');
      }
    } catch (error) {
      console.error('啟動持續模式失敗:', error);
      this.showActionStatus('啟動失敗', 'error');
    }
  }

  async disablePersistentMode() {
    try {
      await chrome.storage.sync.set({ persistentModeEnabled: false });
      const response = await chrome.runtime.sendMessage({ action: 'disablePersistentMode' });
      if (response && response.success) {
        this.isPersistentMode = false;
        this.updateUI();
        this.showActionStatus('持續模式已停用', 'warning');
      } else {
        this.showActionStatus('停用失敗', 'error');
      }
    } catch (error) {
      console.error('停用持續模式失敗:', error);
      this.showActionStatus('停用失敗', 'error');
    }
  }

  updateUI() {
    if (this.isPersistentMode) {
      this.enableBtn.classList.add('hide');
      this.disableBtn.classList.remove('hide');
    } else {
      this.enableBtn.classList.remove('hide');
      this.disableBtn.classList.add('hide');
    }
  }

  showActionStatus(message, type) {
    this.actionStatus.className = `status status-${type}`;
    this.actionStatus.textContent = message;
    this.actionStatus.classList.remove('hide');
    setTimeout(() => { this.actionStatus.classList.add('hide'); }, 5000);
  }
}

document.addEventListener('DOMContentLoaded', () => {
  new PopupController();
});

class PopupController {
  constructor() {
    this.enableBtn = document.getElementById('enablePersistentMode');
    this.disableBtn = document.getElementById('disablePersistentMode');
    this.actionStatus = document.getElementById('actionStatus');
    
    this.isPersistentMode = false;
    this.init();
  }

  async init() {
    // 綁定事件
    this.enableBtn.addEventListener('click', () => this.enablePersistentMode());
    this.disableBtn.addEventListener('click', () => this.disablePersistentMode());

    // 檢查持續模式狀態
    await this.checkPersistentModeStatus();
  }

  async checkPersistentModeStatus() {
    try {
      const result = await chrome.storage.sync.get(['persistentModeEnabled']);
      this.isPersistentMode = result.persistentModeEnabled || false;
      this.updateUI();
    } catch (error) {
      console.error('檢查持續模式狀態失敗:', error);
    }
  }

  async enablePersistentMode() {
    try {
      await chrome.storage.sync.set({ persistentModeEnabled: true });
      
      // 通知 background script 啟動持續模式
      const response = await chrome.runtime.sendMessage({
        action: 'enablePersistentMode'
      });

      if (response && response.success) {
        this.isPersistentMode = true;
        this.updateUI();
        this.showActionStatus('持續模式已啟動', 'success');
        
        // 2秒後關閉 popup
        setTimeout(() => window.close(), 2000);
      } else {
        this.showActionStatus('啟動失敗', 'error');
      }
    } catch (error) {
      console.error('啟動持續模式失敗:', error);
      this.showActionStatus('啟動失敗', 'error');
    }
  }

  async disablePersistentMode() {
    try {
      await chrome.storage.sync.set({ persistentModeEnabled: false });
      
      // 通知 background script 停用持續模式
      const response = await chrome.runtime.sendMessage({
        action: 'disablePersistentMode'
      });

      if (response && response.success) {
        this.isPersistentMode = false;
        this.updateUI();
        this.showActionStatus('持續模式已停用', 'warning');
      } else {
        this.showActionStatus('停用失敗', 'error');
      }
    } catch (error) {
      console.error('停用持續模式失敗:', error);
      this.showActionStatus('停用失敗', 'error');
    }
  }

  updateUI() {
    if (this.isPersistentMode) {
      this.enableBtn.classList.add('hide');
      this.disableBtn.classList.remove('hide');
    } else {
      this.enableBtn.classList.remove('hide');
      this.disableBtn.classList.add('hide');
    }
  }

  showActionStatus(message, type) {
    this.actionStatus.className = `status status-${type}`;
    this.actionStatus.textContent = message;
    this.actionStatus.classList.remove('hide');

    setTimeout(() => {
      this.actionStatus.classList.add('hide');
    }, 5000);
  }
}

// 當 DOM 載入完成時初始化
document.addEventListener('DOMContentLoaded', () => {
  new PopupController();
});