// lib/ui/HistoryPanel.js — 歷史紀錄面板（popup 用）

import { HistoryStore } from '../storage/HistoryStore.js'

const store = new HistoryStore()

export class HistoryPanel {
  /**
   * 渲染歷史紀錄面板到指定容器
   * @param {HTMLElement} container
   */
  async render(container) {
    const history = await store.getAll()
    container.innerHTML = history.length === 0
      ? `<div class="history-empty">尚無歷史紀錄</div>`
      : history.map(entry => this._renderEntry(entry)).join('')
  }

  /**
   * 新增一筆歷史
   * @param {Object} entry - { url, tagName, locators, timestamp }
   */
  async push(entry) {
    await store.push(entry)
  }

  /**
   * 清除歷史
   * @param {HTMLElement} container
   */
  async clear(container) {
    await store.clear()
    if (container) container.innerHTML = `<div class="history-empty">歷史已清除</div>`
  }

  /**
   * 匯出 JSON 格式
   * @param {string|null} filterUrl 僅匯出指定 hostname 的紀錄，null = 全部
   */
  async exportJSON(filterUrl = null) {
    const history = await this._getFiltered(filterUrl)
    const json = JSON.stringify(history.map(e => ({
      id: e.id,
      timestamp: new Date(e.id).toISOString(),
      url: e.url || '',
      tagName: e.tagName || '',
      locators: e.locators || {}
    })), null, 2)
    this._download('locators.json', 'application/json', json)
  }

  /**
   * 匯出 CSV 格式
   * @param {string|null} filterUrl
   */
  async exportCSV(filterUrl = null) {
    const history = await this._getFiltered(filterUrl)
    const header = 'timestamp,url,tag,type,locator'
    const rows = []
    history.forEach(e => {
      const ts = new Date(e.id).toISOString()
      const url = this._csvEscape(e.url || '')
      const tag = this._csvEscape(e.tagName || '')
      if (e.locators) {
        Object.entries(e.locators).forEach(([type, data]) => {
          const val = this._csvEscape(data?.value || '')
          rows.push(`${ts},${url},${tag},${type},${val}`)
        })
      }
    })
    this._download('locators.csv', 'text/csv', header + '\n' + rows.join('\n'))
  }

  /**
   * 匯出 Page Object Model（JS class 格式）
   * @param {string|null} filterUrl
   */
  async exportPOM(filterUrl = null) {
    const history = await this._getFiltered(filterUrl)
    const lines = [
      '// Generated by Element Locator Generator',
      `// Exported at ${new Date().toISOString()}`,
      '',
      'class PageObjects {'
    ]

    history.forEach((e, i) => {
      const name = this._toCamelCase(e.tagName || 'element', i)
      const pw = e.locators?.playwright?.value
      const css = e.locators?.css?.value
      const primary = pw || css || ''
      lines.push(`  /** ${e.url || ''} — <${e.tagName || '?'}> */`)
      if (primary) {
        lines.push(`  get ${name}() { return page.locator(${JSON.stringify(primary)}) }`)
      }
    })

    lines.push('}', '', 'module.exports = { PageObjects }')
    this._download('page-objects.js', 'text/javascript', lines.join('\n'))
  }

  // ─── private ───

  async _getFiltered(filterUrl) {
    const history = await store.getAll()
    if (!filterUrl) return history
    return history.filter(e => {
      try { return new URL(e.url).hostname === filterUrl } catch (_) { return false }
    })
  }

  _csvEscape(val) {
    if (val.includes(',') || val.includes('"') || val.includes('\n')) {
      return '"' + val.replace(/"/g, '""') + '"'
    }
    return val
  }

  _toCamelCase(tag, index) {
    return tag.toLowerCase().replace(/[^a-z0-9]/g, '') + index
  }

  _download(filename, mimeType, content) {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  _renderEntry(entry) {
    const time = new Date(entry.id).toLocaleString('zh-TW', {
      month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit'
    })
    const url = entry.url ? new URL(entry.url).hostname : '未知'
    const tag = entry.tagName || 'element'
    const preview = entry.locators
      ? Object.values(entry.locators).find(v => v)?.value?.substring(0, 60) || ''
      : ''
    return `
      <div class="history-entry" data-id="${entry.id}">
        <div class="history-meta">
          <span class="history-tag">&lt;${tag}&gt;</span>
          <span class="history-url">${url}</span>
          <span class="history-time">${time}</span>
        </div>
        <div class="history-preview">${preview}</div>
      </div>
    `
  }
}
